apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
  labels:
    app: master
spec:
  replicas: 1
  template:
    metadata:
      name: master
      labels:
        app: master
    spec:
      containers:
        - name: master
          image: tomcat
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: master

